import type { Config } from "tailwindcss"

const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/sites/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface-container-highest": "#32353c",
        "surface-tint": "#b0c6ff",
        "on-secondary": "#002f65",
        "inverse-primary": "#0058cb",
        "secondary-container": "#438fff",
        "surface-container": "#1d1f27",
        "on-background": "#e1e2ec",
        "on-primary-container": "#d5dfff",
        "inverse-surface": "#e1e2ec",
        "surface-container-high": "#272a31",
        "secondary-fixed": "#d7e3ff",
        "on-tertiary-fixed-variant": "#394379",
        "on-error-container": "#ffdad6",
        "tertiary-fixed-dim": "#bac3ff",
        "primary": "#b0c6ff",
        "on-secondary-fixed-variant": "#00458f",
        "on-tertiary": "#222c61",
        "on-surface": "#e1e2ec",
        "secondary-fixed-dim": "#abc7ff",
        "surface-container-lowest": "#0c0e15",
        "on-tertiary-fixed": "#0a154b",
        "outline": "#8c909f",
        "on-secondary-container": "#002959",
        "surface": "#11131a",
        "on-primary-fixed-variant": "#00429c",
        "on-surface-variant": "#c2c6d6",
        "error-container": "#93000a",
        "primary-fixed-dim": "#b0c6ff",
        "on-error": "#690005",
        "on-secondary-fixed": "#001b3f",
        "surface-variant": "#32353c",
        "tertiary-fixed": "#dee0ff",
        "error": "#ffb4ab",
        "outline-variant": "#424654",
        "secondary": "#abc7ff",
        "inverse-on-surface": "#2e3038",
        "tertiary": "#bac3ff",
        "tertiary-container": "#565f97",
        "surface-bright": "#373941",
        "on-tertiary-container": "#daddff",
        "primary-container": "#045cd3",
        "primary-fixed": "#d9e2ff",
        "on-primary": "#002d6f",
        "surface-dim": "#11131a",
        "background": "#11131a",
        "surface-container-low": "#191b23",
        "on-primary-fixed": "#001945",
        "deep-contrast": "#0B0F2B",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        md: "24px",
        "margin-mobile": "16px",
        base: "8px",
        "margin-desktop": "48px",
        xs: "4px",
        lg: "40px",
        sm: "12px",
        xl: "64px",
        gutter: "24px",
        "container-max": "1280px",
        "stack-sm": "24px",
        "stack-lg": "80px",
        "stack-md": "40px",
        "stack-xl": "120px",
      },
      animation: {
        'pulse-slow': 'pulse-slow 4s ease-in-out infinite',
      },
      keyframes: {
        'pulse-slow': {
          '0%, 100%': { opacity: '0.4' },
          '50%': { opacity: '0.8' },
        },
      },
      fontFamily: {
        sans: ["Montserrat", "system-ui", "sans-serif"],
      },
      fontSize: {
        "body-sm": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "label-md": ["12px", { lineHeight: "16px", fontWeight: "600" }],
        "body-lg": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "headline-lg-mobile": ["28px", { lineHeight: "34px", fontWeight: "700" }],
        "display-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "title-md": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "headline-lg": ["32px", { lineHeight: "40px", fontWeight: "700" }],
      },
    },
  },
  plugins: [],
}

export default config
