// PixelHub — Constructora Vargas design tokens

export const theme = {
  colors: {
    'on-secondary-fixed-variant': '#36485b',
    'surface': '#f4fafe',
    'surface-variant': '#dde3e7',
    'on-primary': '#ffffff',
    'on-primary-container': '#502600',
    'outline': '#897365',
    'on-tertiary': '#ffffff',
    'on-secondary': '#ffffff',
    'inverse-surface': '#2b3135',
    'tertiary-fixed': '#7efba4',
    'inverse-primary': '#ffb783',
    'surface-container-lowest': '#ffffff',
    'on-secondary-fixed': '#091d2e',
    'on-error-container': '#93000a',
    'tertiary': '#006d37',
    'on-secondary-container': '#526478',
    'tertiary-container': '#29af61',
    'secondary-fixed': '#d1e4fb',
    'primary-fixed-dim': '#ffb783',
    'on-primary-fixed-variant': '#713700',
    'surface-tint': '#944a00',
    'on-error': '#ffffff',
    'error': '#ba1a1a',
    'outline-variant': '#dcc1b1',
    'surface-container': '#e9eff3',
    'surface-container-low': '#eff4f8',
    'primary': '#944a00',
    'on-background': '#161c20',
    'secondary': '#4e6073',
    'secondary-fixed-dim': '#b5c8df',
    'tertiary-fixed-dim': '#61de8a',
    'surface-dim': '#d5dbdf',
    'on-surface': '#161c20',
    'secondary-container': '#cfe2f9',
    'error-container': '#ffdad6',
    'inverse-on-surface': '#ecf1f6',
    'primary-fixed': '#ffdcc5',
    'on-tertiary-fixed': '#00210c',
    'on-surface-variant': '#564337',
    'background': '#f4fafe',
    'surface-bright': '#f4fafe',
    'on-primary-fixed': '#301400',
    'surface-container-high': '#e3e9ed',
    'primary-container': '#e67e22',
    'on-tertiary-fixed-variant': '#005228',
    'surface-container-highest': '#dde3e7',
    'on-tertiary-container': '#003a1a',
  } as const,

  fonts: {
    'headline-md': 'Montserrat',
    'button': 'Montserrat',
    'headline-lg': 'Bebas Neue',
    'display-lg': 'Bebas Neue',
    'body-lg': 'Open Sans',
    'body-md': 'Open Sans',
    'label-bold': 'Montserrat',
  } as const,

  fontSizes: {
    'headline-md': { fontSize: '24px', lineHeight: '32px', fontWeight: 700 as const },
    'button': { fontSize: '16px', lineHeight: '16px', fontWeight: 600 as const },
    'headline-lg': { fontSize: '48px', lineHeight: '48px', letterSpacing: '0.02em', fontWeight: 400 as const },
    'display-lg': { fontSize: '72px', lineHeight: '72px', letterSpacing: '0.02em', fontWeight: 400 as const },
    'body-lg': { fontSize: '18px', lineHeight: '28px', fontWeight: 400 as const },
    'body-md': { fontSize: '16px', lineHeight: '24px', fontWeight: 400 as const },
    'label-bold': { fontSize: '14px', lineHeight: '20px', fontWeight: 600 as const },
  } as const,

  spacing: {
    'margin-desktop': '64px',
    'stack-md': '24px',
    'stack-xs': '4px',
    'stack-xl': '80px',
    'stack-sm': '12px',
    'base': '8px',
    'stack-lg': '48px',
    'margin-mobile': '16px',
    'gutter': '24px',
  } as const,

  radii: {
    DEFAULT: '4px',
    lg: '4px',
    xl: '8px',
    full: '9999px',
  } as const,
}

export type Theme = typeof theme
